# Generated by Django 6.0.3 on 2026-07-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_role',
            field=models.CharField(choices=[('requester', 'Requester'), ('approver', 'Approver'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='approver', max_length=20),
        ),
    ]
