# Generated by Django 6.0.3 on 2026-03-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='orders.orderitem')),
            ],
            options={
                'db_table': 'dispatch_logs',
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
