# Generated by Django 6.0.3 on 2026-03-29 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('tenant', models.CharField(blank=True, default='', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='catalog.servicetemplate')),
            ],
            options={
                'db_table': 'availability_rules',
            },
        ),
        migrations.CreateModel(
            name='ContextRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_key', models.CharField(max_length=50)),
                ('context_field', models.CharField(max_length=50)),
                ('allowed_values', models.JSONField(default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_restrictions', to='catalog.servicetemplate')),
            ],
            options={
                'db_table': 'context_restrictions',
            },
        ),
        migrations.CreateModel(
            name='UserTenantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tenant_assignments',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
